<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="<?php echo $this->getHeaderWidth() ?>"><?php echo $this->getHeaderHtml() ?></td>
            <td class="form-buttons"><?php echo $this->getButtonsHtml() ?></td>
        </tr>
    </table>
</div>

<div class="entry-edit">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Antifraud Data'); ?></h4>
        </div>
        <div id="log_details_fieldset" class="log-details">
            <table cellspacing="0" class="log-info table">
                <col width="5%" />
                <col />
                <tbody>
                    <tr>
                        <th><?php echo $this->__('ID #'); ?></th>
                        <td><?php echo $this->getIdHtml() ?></td>
                    </tr>
                    <tr>
                        <th><?php echo $this->__('Order ID'); ?></th>
                        <td>
                            <a href="<?php echo $this->getOrderIdUrlHtml(); ?>">
                                <?php echo $this->getOrderIncrementIdHtml() ?>
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <th><?php echo $this->__('Transaction ID'); ?></th>
                        <td><?php echo $this->getTransactionIdHtml() ?></td>
                    </tr>
                    <tr>
                        <th><?php echo $this->__('Status'); ?></th>
                        <td><?php echo $this->getStatusHtml() ?></td>
                    </tr>
                    <tr>
                        <th><?php echo $this->__('Score'); ?></th>
                        <td><?php echo $this->getScoreHtml(); ?></td>
                    </tr>
                    <tr>
                        <th><?php echo $this->__('Created At'); ?></th>
                        <td><?php echo $this->getCreatedAtHtml(); ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="entry-edit">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Antifraud Details'); ?></h4>
        </div>
        <div class="log-details-tree">
            <?php echo $this->getChildHtml('sales_antifraud.detail.tree') ?>
        </div>
    </div>
</div>
