<?php
$url = 'https://' . $this->getDomain();
$merchantId = $this->getMerchantId();
$sessionId = $this->getSessionId();
$orgId = $this->getOrgId();
?>
<p style="background:url(<?php echo $url; ?>/fp/clear.png?org_id=<?php echo $orgId; ?>&amp;session_id=<?php echo $merchantId; ?><?php echo $sessionId; ?>&amp;m=1)"></p>
<img src="<?php echo $url; ?>/fp/clear.png?org_id=<?php echo $orgId; ?>&amp;session_id=<?php echo $merchantId; ?><?php echo $sessionId; ?>&amp;m=2" alt="">

<object type="application/x-shockwave-flash" data="<?php echo $url; ?>/fp/fp.swf?org_id=<?php echo $orgId; ?>&amp;session_id=<?php echo $merchantId; ?><?php echo $sessionId; ?>" width="1" height="1"
id="thm_fp">
<param name="movie" value="<?php echo $url; ?>/fp/fp.swf?org_id=<?php echo $orgId; ?>&amp;session_id=<?php echo $merchantId; ?><?php echo $sessionId; ?>" />
<div></div>
</object>

<script src="<?php echo $url; ?>/fp/check.js?org_id=<?php echo $orgId; ?>&amp;session_id=<?php echo $merchantId; ?><?php echo $sessionId; ?>" type="text/javascript">
</script> 