<div class="page-head">
    <h3><?php echo $this->__('Redirecting to payment page') ?></h3>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php echo $this->getChildHtml('braspag_payment_form'); ?>

<script type="text/javascript">  
    // <![CDATA[  
        document.observe('dom:loaded', function() {  
            $('webjump_braspagpagador_post').submit();
        });   
    // ]]>  
</script>