<?php
$_code = $this->getMethodCode();

//Retrieve data submited
$_additionalInformation = $this->getInfoData('additional_information');

?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li id="<?php echo $_code ?>_cc_token_div">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <label for="<?php echo $_code ?>_cc_token" class="required"><em>*</em><?php echo $this->__('Saved Credit Cards (JustClick)') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_cc_token" name="payment[payment_request][cc_token]" class="required-entry" title="<?php echo $this->__('Saved Credit Cards (JustClick)') ?>">
                <option value=""><?php echo $this->__('--Please Select--')?></option>
                <?php $_ccType = isset($_additionalInformation['payment_request']['cc_token']) ? $_additionalInformation['payment_request']['cc_token'] : null; ?>
                <?php foreach ($this->getAvailableCards() as $_card): ?>
                    <option value="<?php echo $_card['token'] ?>"<?php if($_card['token']==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_card['alias'] ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </li>
    <?php if ($this->isShowCardVerifyCode()): ?>
        <li id="<?php echo $_code ?>_cc_token_cvv_div">
            <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
            <div class="input-box">
                <div class="v-fix">
                    <input type="text" pattern="\d*" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry" id="<?php echo $_code ?>_cc_cid" name="payment[payment_request][cc_cid]" value="" />
                </div>
                <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
            </div>
        </li>
    <?php endif ?>
    <li>
        <label for="<?php echo $_code ?>_installments" class="required"><em>*</em><?php echo $this->__('Installments') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <?php $_installments = isset($_additionalInformation['payment_request']['installments']) ? $_additionalInformation['payment_request']['installments'] : null; ?>
                <select id="<?php echo $_code ?>_installments" name="payment[payment_request][installments]" class="number required-entry">
                    <?php foreach ($this->getInstallments() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_installments): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>
</ul>
