<?php 
$_code = $this->getMethodCode();

//Retrieve data submited
$_additionalInformation = $this->getInfoData('additional_information');

$numPayments = 0;
?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
<?php for($_paymentRequestIndex = 0; $_paymentRequestIndex <= $numPayments; $_paymentRequestIndex++): ?>
	<li id="<?php echo $_code ?>_<?php echo $_paymentRequestIndex; ?>_dc_type_div">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <label for="<?php echo $_code ?>_dc_type" class="required"><em>*</em><?php echo $this->__('Debit Card Type') ?></label>
        <div class="input-box">
            <select autocomplete="off" id="<?php echo $_code ?>_<?php echo $_paymentRequestIndex; ?>_dc_type" name="payment[payment_request][<?php echo $_paymentRequestIndex; ?>][dc_type]" class="required-entry" title="<?php echo $this->__('Debit Card Type') ?>">
                <option value=""><?php echo $this->__('--Please Select--')?></option>
            <?php echo $_dcType = isset($_additionalInformation['payment_request'][$_paymentRequestIndex]['dc_type']) ? $_additionalInformation['payment_request'][$_paymentRequestIndex]['dc_type'] : null; ?>
            <?php foreach ($this->getDcAvailableTypes() as $_typeCode => $_typeName): ?>
                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_dcType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
    <li id="<?php echo $_code ?>_<?php echo $_paymentRequestIndex; ?>_dc_owner_div">
		<label for="<?php echo $_code ?>_<?php echo $_paymentRequestIndex; ?>_dc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
        <div class="input-box">
            <input autocomplete="off" type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_<?php echo $_paymentRequestIndex; ?>_dc_owner" name="payment[payment_request][<?php echo $_paymentRequestIndex; ?>][dc_owner]" value="<?php if (isset($_additionalInformation['payment_request'][$_paymentRequestIndex]['dc_owner'])) { echo $this->escapeHtml($_additionalInformation['payment_request'][$_paymentRequestIndex]['dc_owner']); } ?>" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_<?php echo $_paymentRequestIndex; ?>_dc_number" class="required"><em>*</em><?php echo $this->__('Debit Card Number') ?></label>
        <div class="input-box">
            <input autocomplete="off" type="text" pattern="\d*" id="<?php echo $_code ?>_<?php echo $_paymentRequestIndex; ?>_dc_number" name="payment[payment_request][<?php echo $_paymentRequestIndex; ?>][dc_number]" title="<?php echo $this->__('Debit Card Number') ?>" class="input-text required-entry" value="" />
        </div>
    </li>
    <li id="<?php echo $_code ?>_<?php echo $_paymentRequestIndex; ?>_dc_type_exp_div">
        <label for="<?php echo $_code ?>_<?php echo $_paymentRequestIndex; ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <select autocomplete="off" id="<?php echo $_code ?>_<?php echo $_paymentRequestIndex; ?>_expiration" name="payment[payment_request][<?php echo $_paymentRequestIndex; ?>][dc_exp_month]" class="month validate-cc-exp required-entry">
                <?php $_dcExpMonth = isset($_additionalInformation['payment_request'][$_paymentRequestIndex]['dc_exp_month']) ? $_additionalInformation['payment_request'][$_paymentRequestIndex]['dc_exp_month'] : null; ?>
                <?php foreach ($this->getCardMonths() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_dcExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_dcExpYear = isset($_additionalInformation['payment_request'][$_paymentRequestIndex]['dc_exp_year']) ? $_additionalInformation['payment_request'][$_paymentRequestIndex]['dc_exp_year'] : null; ?>
                <select autocomplete="off" id="<?php echo $_code ?>_<?php echo $_paymentRequestIndex; ?>_expiration_yr" name="payment[payment_request][<?php echo $_paymentRequestIndex; ?>][dc_exp_year]" class="year required-entry">
                <?php foreach ($this->getCardYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_dcExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>
    <li id="<?php echo $_code ?>_<?php echo $_paymentRequestIndex; ?>_dc_type_cvv_div">
        <label for="<?php echo $_code ?>_<?php echo $_paymentRequestIndex; ?>_dc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <input autocomplete="off" type="text" pattern="\d*" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry" id="<?php echo $_code ?>_<?php echo $_paymentRequestIndex; ?>_dc_cid" name="payment[payment_request][<?php echo $_paymentRequestIndex; ?>][dc_cid]" value="" />
            </div>
            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
        </div>
    </li>
<?php endfor; ?>
</ul>
