<?php 
	$_code = $this->getMethodCode();
	$_paymentRequestIndex = 0;
?>
<ul class="form-list" id="payment_form_<?php echo $_code  ?>" style="display:none;">
	<li id="<?php echo $_code ?>_<?php echo $_paymentRequestIndex; ?>_cc_type_div">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_<?php echo $_paymentRequestIndex; ?>_cc_type" name="payment[payment_request][<?php echo $_paymentRequestIndex; ?>][cc_type]" class="required-entry" title="<?php echo $this->__('Credit Card Type') ?>">
                <option value=""><?php echo $this->__('--Please Select--')?></option>
	            <?php foreach ($this->getAvailableTypes() as $key => $label): ?>
                    <option value="<?php echo $key ?>"><?php echo $label ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </li>
    <?php if($this->isInstallmentsEnabled()): ?>
        <li>
            <label for="<?php echo $_code ?>_<?php echo $_paymentRequestIndex; ?>_installments" class="required"><em>*</em><?php echo $this->__('Installments') ?></label>
            <div class="input-box">
                <div class="v-fix">
                    <select id="<?php echo $_code ?>_<?php echo $_paymentRequestIndex; ?>_installments" name="payment[payment_request][<?php echo $_paymentRequestIndex; ?>][installments]" class="number required-entry">
                    <?php foreach ($this->getInstallments() as $key =>$value): ?>
                        <option value="<?php echo $key ?>"><span><?php echo $this->__('%1$sx %2$s without interest', $key, $value); ?></span></option>
                    <?php endforeach ?>
                    </select>
                </div>
            </div>
        </li>
    <?php endif;?>
    <?php if ($this->isJustclickEnabled()): ?>
        <li>
            <div class="input-box">
                <div class="v-fix">
                    <input type="checkbox" name="payment[payment_request][<?php echo $_paymentRequestIndex; ?>][cc_justclick]" id="<?php echo $_code ?>_<?php echo $_paymentRequestIndex; ?>_cc_justclick"/><label for="<?php echo $_code ?>_<?php echo $_paymentRequestIndex; ?>_cc_justclick"><em>*</em><?php echo $this->__('add To Braspag JustClick') ?></label>
                </div>
            </div>
        </li>
    <?php endif ?>
</ul>
