<?php 
$_code = $this->getMethodCode();

$_paymentInstructions = $this->getPaymentInstructions();
?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
	<li>
		<input type="hidden" name="payment[payment_request][billet_type]" value="<?php echo $this->getBilletType();?>">
		<?php if (!empty($_paymentInstructions)): ?>
			<?php echo $_paymentInstructions; ?>
		<?php endif; ?>
	</li>
</ul>
